// <auto-generated />
using System;
using Delivery.EntityFramework.Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Delivery.EntityFramework.Core.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20231016102003_initUser")]
    partial class initUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Lingau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<decimal>("lingau_Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("person_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("person_Id", "del_Status");

                    b.ToTable("sys_Lingau", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Lingau_OptLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<string>("opt_BeUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("opt_BeginAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("opt_EndAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("opt_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opt_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("opt_User", "opt_BeUser", "del_Status");

                    b.ToTable("sys_Lingau_OptLog", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<decimal>("order_BenginLat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("order_BenginLng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("order_BenginPlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_CreateDeptId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_CreateDeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("order_EndLat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("order_EndLng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("order_EndPlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order_GoddsNums")
                        .HasColumnType("int");

                    b.Property<double>("order_GoodsDelivery")
                        .HasColumnType("float");

                    b.Property<string>("order_GoodsHight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("order_GoodsLong")
                        .HasColumnType("float");

                    b.Property<string>("order_GoodsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("order_GoodsPrice")
                        .HasColumnType("float");

                    b.Property<string>("order_GoodsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("order_GoodsWeight")
                        .HasColumnType("float");

                    b.Property<double>("order_GoodsWidth")
                        .HasColumnType("float");

                    b.Property<string>("order_JobStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("order_PathDistance")
                        .HasColumnType("float");

                    b.Property<string>("order_PayIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_PayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_RiderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_RiderPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("del_Status");

                    b.ToTable("sys_Order", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Order_TagOrReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<bool>("isEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("order_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("order_TagOrReport_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("tagManager_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tag_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("order_Id");

                    b.HasIndex("order_TagOrReport_Name", "order_Id", "del_Status");

                    b.ToTable("sys_Order_TagOrReport", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<bool>("isEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("tag_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("tag_Name", "del_Status");

                    b.ToTable("sys_Tag", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Tag_Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("tag_Id")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tag_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("tag_Id", "tag_Type", "del_Status");

                    b.ToTable("sys_Tag_Manager", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.SystemEntitys.SystemDict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dict_JsonValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dict_Key")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("dict_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dict_Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<bool?>("isSystemBuilt")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("dict_Key", "del_Status");

                    b.ToTable("sys_Dict", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.SystemEntitys.SystemFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<string>("file_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("del_Status");

                    b.ToTable("sys_File", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.SystemEntitys.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<string>("log_ApiMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_ApiPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_ElapsedMilliseconds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_OptIP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("log_OptPort")
                        .HasColumnType("int");

                    b.Property<string>("log_OptTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_OptUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("log_Os")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("log_Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("log_OptIP", "log_OptUser", "log_Type", "del_Status");

                    b.ToTable("sys_Log", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Dept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("dept_ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dept_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_SimpleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("del_Status");

                    b.ToTable("sys_Dept", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<string>("job_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("dept_Id");

                    b.HasIndex("del_Status", "dept_Id");

                    b.ToTable("sys_Job", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Limit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<string>("limit_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("del_Status");

                    b.ToTable("sys_Limit", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Limit_Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<bool?>("limit_Add")
                        .HasColumnType("bit");

                    b.Property<bool?>("limit_Del")
                        .HasColumnType("bit");

                    b.Property<bool?>("limit_Edit")
                        .HasColumnType("bit");

                    b.Property<Guid>("limit_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("limit_Query")
                        .HasColumnType("bit");

                    b.Property<Guid>("menu_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("menu_IdArray")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("limit_Id");

                    b.HasIndex("menu_Id");

                    b.HasIndex("del_Status", "limit_Id", "menu_Id");

                    b.ToTable("sys_Limit_Menu", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<bool?>("isOuterJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("menu_ComponentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu_FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu_FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu_Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu_Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("menu_ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("menu_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("menu_PlatFrom")
                        .HasColumnType("int");

                    b.Property<string>("menu_SimpleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("del_Status");

                    b.ToTable("sys_Menu", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("job_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("per_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_IdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_JobStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_NormalizedPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_Politics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_SimpleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_UserPwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("dept_Id");

                    b.HasIndex("job_Id");

                    b.HasIndex("del_Status", "dept_Id");

                    b.ToTable("sys_Person", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("create_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("del_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("del_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("del_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("dept_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("expand_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("expand_Order")
                        .HasColumnType("int");

                    b.Property<bool>("isEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("limit_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("person_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("update_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_LoginPwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_LoginPwdCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("dept_Id");

                    b.HasIndex("limit_Id");

                    b.HasIndex("person_Id");

                    b.HasIndex("del_Status", "limit_Id", "person_Id");

                    b.ToTable("sys_User", (string)null);
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Order_TagOrReport", b =>
                {
                    b.HasOne("Delivery.Domains.OrderEntitys.Order", "orderInfo")
                        .WithMany("order_TagOrReportInfos")
                        .HasForeignKey("order_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("orderInfo");
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Tag_Manager", b =>
                {
                    b.HasOne("Delivery.Domains.OrderEntitys.Tag", "TagInfo")
                        .WithMany("tag_ManagerList")
                        .HasForeignKey("tag_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TagInfo");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Job", b =>
                {
                    b.HasOne("Delivery.Domains.UserEntitys.Dept", "deptInfo")
                        .WithMany("jobInfos")
                        .HasForeignKey("dept_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("deptInfo");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Limit_Menu", b =>
                {
                    b.HasOne("Delivery.Domains.UserEntitys.Limit", "limitInfo")
                        .WithMany("limit_Menus")
                        .HasForeignKey("limit_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Delivery.Domains.UserEntitys.Menu", "menuInfo")
                        .WithMany()
                        .HasForeignKey("menu_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("limitInfo");

                    b.Navigation("menuInfo");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Person", b =>
                {
                    b.HasOne("Delivery.Domains.UserEntitys.Dept", "deptInfo")
                        .WithMany("personInfos")
                        .HasForeignKey("dept_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Delivery.Domains.UserEntitys.Job", "jobInfo")
                        .WithMany("personInfos")
                        .HasForeignKey("job_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("deptInfo");

                    b.Navigation("jobInfo");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.User", b =>
                {
                    b.HasOne("Delivery.Domains.UserEntitys.Dept", "deptInfo")
                        .WithMany("userInfos")
                        .HasForeignKey("dept_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Delivery.Domains.UserEntitys.Limit", "limitInfo")
                        .WithMany("userInfos")
                        .HasForeignKey("limit_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Delivery.Domains.UserEntitys.Person", "personInfo")
                        .WithMany("userInfos")
                        .HasForeignKey("person_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("deptInfo");

                    b.Navigation("limitInfo");

                    b.Navigation("personInfo");
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Order", b =>
                {
                    b.Navigation("order_TagOrReportInfos");
                });

            modelBuilder.Entity("Delivery.Domains.OrderEntitys.Tag", b =>
                {
                    b.Navigation("tag_ManagerList");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Dept", b =>
                {
                    b.Navigation("jobInfos");

                    b.Navigation("personInfos");

                    b.Navigation("userInfos");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Job", b =>
                {
                    b.Navigation("personInfos");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Limit", b =>
                {
                    b.Navigation("limit_Menus");

                    b.Navigation("userInfos");
                });

            modelBuilder.Entity("Delivery.Domains.UserEntitys.Person", b =>
                {
                    b.Navigation("userInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
